sudo: required
services:
    -docker

before_install:
  docker build -t react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true react-test npm test

after_success:
  - docker build -t manjits/multi-client ./client
  - docker build -t manjits/multi-nginx ./nginx
  - docker build -t manjits/multi-server ./server
  - docker build -t manjits/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_ID" --password-stdin
  - docker push manjits/multi-client
  - docker push manjits/multi-nginx
  - docker push manjits/multi-server
  - docker push manjits/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-360109119318
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY  

