sudo: required
services:
    -docker

before_install:
  docker build -t react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true react-test npm test

after_success:
  - docker build -t manjits/multi-client ./client
  - docker build -t manjits/multi-nginx ./nginx
  - docker build -t manjits/multi-server ./server
  - docker build -t manjits/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_ID" --password-stdin
  - docker push manjits/multi-client
  - docker push manjits/multi-nginx
  - docker push manjits/multi-server
  - docker push manjits/multi-worker


